empmanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #加载app子路由user
    url(r'^user/',include('user.urls',namespace='user')),

    url(r'^simple/',include('simple.urls',namespace='simple'))


]

user/urls.py
from django.conf.urls import url
from user import views

urlpatterns=[
    url(r'^login/',views.login,name='login'),
    url(r'^regist/',views.regist,name='regist'),
    url(r'^userDetail/',views.userDetail,name='userDetail'),
    url(r'^userList/',views.userList,name='userList'),
    url(r'^delete/',views.delete,name='delete'),
    url(r'^update/',views.update,name='update'),
    url(r'^quit/',views.quit,name='quit'),
    url(r'^userDetail1/',views.userDetail1,name='userDetail1'),
    url(r'^select/',views.select,name='select'),
    url(r'^verify/',views.verify,name='verify')
]

templates/login.html
{% load static %}
<html>
	<head>
		<title>login</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	</head>

	<body>
		<div id="wrap">
			<div id="top_content">
				<div id="header">
					<div id="rightheader">
						<p>
							特斯拉（上海）有限公司
							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">员工管理系统</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						登录
					</h1>
					<form action="{% url 'user:login' %}" method="post">
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									用户名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="username" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									密码:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="pwd" />
								</td>
							</tr>
                        {#   验证码功能                         #}
                            <tr>
								<td valign="middle" align="right">
									验证码:
								</td>
								<td valign="middle" align="left">
									<img src="{% url 'user:verify' %}" alt="">
								</td>
							</tr>
                            <tr>
							    <td valign="middle" align="right">
									请输入:
							    </td>
							    <td valign="middle" align="left">
									<input type="text" class="inputgri" name="vcode" />
							    </td>
							</tr>


						</table>
						<p>
							<input type="submit" class="button" 
							value="&nbsp;确定&nbsp;" />
							<a href="{% url 'user:regist' %}">还没有帐户，请点击这儿注册</a>
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					huangsc021@163.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/regist.html
{% load static %}
<html>
	<head>
		<title>regist</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	</head>
	<body>
		<div id="wrap">
			<div id="top_content">
				<div id="header">
					<div id="rightheader">
						<p>
							特斯拉（上海）有限公司
							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">员工管理系统</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>

				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						注册
					</h1>
					<form action="{% url 'user:regist' %}" method="post">
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									用户名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="username" />
                                    {% if err %}
                                        {{ err }}
                                    {% endif %}
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									真实姓名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									密码:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="pwd" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									年龄:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="age" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									性别:
								</td>
								<td valign="middle" align="left">
									男
									<input type="radio" class="inputgri" name="sex" value="m"
										checked="checked" />
									女
									<input type="radio" class="inputgri" name="sex" value="f" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									电话:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="phone" />
								</td>
							</tr>
						</table>
						<p>
							<input type="submit" class="button" value="Submit &raquo;" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					huangsc021@126.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/select.html
<html>
	<head>
		<title>emplist</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
		<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css" />
	</head>
	<body>
		<div id="wrap">
			<div id="top_content">
				<div id="header">
					<div id="rightheader">
						<p>
                            查询时间：{{ now }}
							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">员工管理系统</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>

				<div id="content">
					<p id="whereami">
					</p>
                    <div style="margin-bottom:15px">
                        <form action="{% url 'user:select' %}" method="post">
                            ID: <input type="text" name="ID" style="width: 120px">
                            姓名: <input type="text" name="name" style="width: 120px">
                            性别:
                            <select name="sex" style="height: 30px" >
                                <option value=""></option>
                                <option value="m">男</option>
                                <option value="f">女</option>
                            </select>
                            年龄: <input type="text" name="age" style="width: 120px">
                            <input type="submit" value="搜索" style="width: 80px">
                        </form>
                    </div>
					<table class="table">
						<tr class="table_header">
							<td>
								ID
							</td>
							<td>
								姓名
							</td>
							<td>
								性别
							</td>
							<td>
								年龄
							</td>
							<td>
                                操作
							</td>
						</tr>

						{% for user in user_list %}
							<tr class="row1">
								<td>
									{{ user.id }}
								</td>
								<td>
									<a href="{% url 'user:userDetail1' %}?uid={{ user.id }}">
                                        {{ user.name }}
									</a>
								</td>
								<td>
                                    {% if user.sex == 'm' %}
                                       男
                                    {% else %}
                                       女
								    {% endif %}
								</td>
								<td>
									{{ user.age }}
								</td>
								<td>
{#                                    1.这是请求参数#}
{#									<a href="{% url 'user:delete' %}/?uid={{ user.id }}">删除</a>#}
{#                                    2.路由参数#}
                                    <a href="{% url 'user:delete' %}?uid={{ user.id }}">删除</a>
									<a href='{% url 'user:update' %}?uid={{ user.id }}'>修改</a>
								</td>
							</tr>
						{% endfor %}
					</table>
					<p>
                    {#                         改成添加员工#}
						<input type="button" class="button" value="退出系统"
							onclick="location='{% url 'user:quit' %}'" />
                    </p>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					huangsc@163.com
				</div>
			</div>
		</div>

<script src="/static/js/jquery-3.5.1.slim.min.js"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
	</body>
</html>

templates/update.html
{% load static %}
<html>
	<head>
		<title>regist</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	</head>
	<body>
		<div id="wrap">
			<div id="top_content">
				<div id="header">
					<div id="rightheader">
						<p>
							2009/11/20
							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">Main</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>

				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						修改
					</h1>
					<form action="{% url 'user:update' %}" method="post">
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
				     		    <input type="hidden" name="uid" value="{{ user.id }}"/>
								<td valign="middle" align="right">
									真实姓名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" value="{{ user.name }}"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									密码:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="pwd" value="{{ user.pwd }}"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									年龄:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="age" value="{{ user.age }}"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									性别:
								</td>
                                <td valign="middle" align="left">
{#                                总归会显示一组默认的情况#}
                                {% if user.sex == 'm' %}
                                    男<input type="radio" class="inputgri" name="sex" value="m" checked="checked" />
                                    女<input type="radio" class="inputgri" name="sex" value="f" />
                                {% else %}
                                    男<input type="radio" class="inputgri" name="sex" value="m" />
                                    女<input type="radio" class="inputgri" name="sex" value="f" checked="checked"/>
                                {% endif  %}
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									电话:
								</td>
								<td valign="middle" align="left">
                                    <input type="text" class="inputgri" name="phone" value="{{ user.phone }}"/>
								</td>
							</tr>
						</table>
						<p>
							<input type="submit" class="button" value="Submit &raquo;" />
						</p>
					</form>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					huangsc021@126.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/userDetail.html
{% load static %}
<html>
	<head>
		<title>update Emp</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	</head>
	<body>
		<div id="wrap">
			<div id="top_content">
				<div id="header">
					<div id="rightheader">
						<p>
                            登录时间：{{ now }}
							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">员工管理系统</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>

				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						User Detail:
					</h1>
					<table class="table">
						<tr>
							<td>
								姓名
							</td>
							<td>
								电话
							</td>
						</tr>
						<tr>
							<td>
								{{ user.name }}
							</td>
							<td>
								{{ user.phone }}
							</td>
						</tr>
					</table>
					<br/>
					<h1>
						Load Photo:
					</h1>
	
						<form action="userDetail.html" method="post"
							enctype="multipart/form-data">
							Upload File Name:
							<input type="file" name="file1" />
							<input type="submit" value="confirm" />
						</form>

					<h1>
						view photo:
					</h1>
					<table>
								<tr>
									<td>
										<img src="/static/upload/boy001.jpg" width="300"
											height="300" />
									</td>
								</tr>
					</table>
				</div>
				<input type="button" onclick="location='{% url 'user:userList' %}?page={{ 1 }}'" value="查看所有用户"/>
			</div>
			<div id="footer">
				<div id="footer_bg">
					huangsc@163.com
				</div>
			</div>
		</div>
	</body>
</html>

templates/userList.html
<html>
	<head>
		<title>emplist</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
		<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css" />
	</head>
	<body>
		<div id="wrap">
			<div id="top_content">
				<div id="header">
					<div id="rightheader">
						<p>
                            查询时间：{{ now }}
							<br />
						</p>
					</div>
					<div id="topheader">
						<h1 id="title">
							<a href="#">员工管理系统</a>
						</h1>
					</div>
					<div id="navigation">
					</div>
				</div>

				<div id="content">
					<p id="whereami">
					</p>
                    <div style="margin-bottom:15px">
                        <form action="{% url 'user:select' %}" method="post">
                            ID: <input type="text" name="ID" style="width: 120px">
                            姓名: <input type="text" name="name" style="width: 120px">
                            性别:
                            <select name="sex" style="height: 30px" >
                                <option value=""></option>
                                <option value="m">男</option>
                                <option value="f">女</option>
                            </select>
                            年龄: <input type="text" name="age" style="width: 120px">
                            <input type="submit" value="搜索" style="width: 80px">
                        </form>
                    </div>
					<table class="table">
						<tr class="table_header">
							<td>
								ID
							</td>
							<td>
								姓名
							</td>
							<td>
								性别
							</td>
							<td>
								年龄
							</td>
							<td>
                                操作
							</td>
						</tr>

						{% for user in current_page %}
							<tr class="row1">
								<td>
									{{ user.id }}
								</td>
								<td>
									<a href="{% url 'user:userDetail1' %}?uid={{ user.id }}">
                                        {{ user.name }}
									</a>
								</td>
								<td>
                                    {% if user.sex == 'm' %}
                                       男
                                    {% else %}
                                       女
								    {% endif %}
								</td>
								<td>
									{{ user.age }}
								</td>
								<td>
{#                                    1.这是请求参数#}
{#									<a href="{% url 'user:delete' %}/?uid={{ user.id }}">删除</a>#}
{#                                    2.路由参数#}
                                    <a href="{% url 'user:delete' %}?uid={{ user.id }}">删除</a>
									<a href='{% url 'user:update' %}?uid={{ user.id }}'>修改</a>
								</td>
							</tr>
						{% endfor %}
					</table>
					<p>
                    {#                         改成添加员工#}
						<input type="button" class="button" value="退出系统"
							onclick="location='{% url 'user:quit' %}'" />
                        {#分页功能#}
                        <nav aria-label="Page navigation">
                          <ul class="pagination">
                            {#  显示页码索引                        #}
                            {% if current_page.has_previous %}
                                <li class="page-item"><a class="page-link" href="{% url 'user:userList' %}?page={{ current_page.previous_page_number }}">上一页</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="#">上一页</a></li>
                            {% endif %}
                            {% for pg in pages %}
                                {% if pg == current_page_num %}
                                    <li class="page-item"><a class="page-link">{{ pg }}</a></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="{% url 'user:userList' %}?page={{ pg }}">{{ pg }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if current_page.has_next %}
                                <li class="page-item"><a class="page-link" href="{% url 'user:userList' %}?page={{ current_page.next_page_number }}">下一页</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="#">下一页</a></li>
                            {% endif %}
                          </ul>
                        </nav>
					</p>
				</div>
			</div>
			<div id="footer">
				<div id="footer_bg">
					huangsc@163.com
				</div>
			</div>
		</div>

<script src="/static/js/jquery-3.5.1.slim.min.js"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
	</body>
</html>